package com.TCA.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseIssueRecord<M extends BaseIssueRecord<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}

	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setUSERCODE(java.lang.String USERCODE) {
		set("USERCODE", USERCODE);
		return (M)this;
	}

	public java.lang.String getUSERCODE() {
		return getStr("USERCODE");
	}

	public M setCOSTUNITFROM(java.lang.String COSTUNITFROM) {
		set("COSTUNITFROM", COSTUNITFROM);
		return (M)this;
	}

	public java.lang.String getCOSTUNITFROM() {
		return getStr("COSTUNITFROM");
	}

	public M setWORKPLACEFROM(java.lang.String WORKPLACEFROM) {
		set("WORKPLACEFROM", WORKPLACEFROM);
		return (M)this;
	}

	public java.lang.String getWORKPLACEFROM() {
		return getStr("WORKPLACEFROM");
	}

	public M setCOSTUNITTO(java.lang.String COSTUNITTO) {
		set("COSTUNITTO", COSTUNITTO);
		return (M)this;
	}

	public java.lang.String getCOSTUNITTO() {
		return getStr("COSTUNITTO");
	}

	public M setWORKPLACETO(java.lang.String WORKPLACETO) {
		set("WORKPLACETO", WORKPLACETO);
		return (M)this;
	}

	public java.lang.String getWORKPLACETO() {
		return getStr("WORKPLACETO");
	}

	public M setTOOLID(java.lang.String TOOLID) {
		set("TOOLID", TOOLID);
		return (M)this;
	}

	public java.lang.String getTOOLID() {
		return getStr("TOOLID");
	}

	public M setCOUNT(java.lang.Integer COUNT) {
		set("COUNT", COUNT);
		return (M)this;
	}

	public java.lang.Integer getCOUNT() {
		return getInt("COUNT");
	}

	public M setISSUETIME(java.lang.String ISSUETIME) {
		set("ISSUETIME", ISSUETIME);
		return (M)this;
	}

	public java.lang.String getISSUETIME() {
		return getStr("ISSUETIME");
	}

	public M setDEADLINE(java.lang.String DEADLINE) {
		set("DEADLINE", DEADLINE);
		return (M)this;
	}

	public java.lang.String getDEADLINE() {
		return getStr("DEADLINE");
	}

	public M setSTATE(java.lang.Integer STATE) {
		set("STATE", STATE);
		return (M)this;
	}

	public java.lang.Integer getSTATE() {
		return getInt("STATE");
	}

	public M setTYPE(java.lang.Integer TYPE) {
		set("TYPE", TYPE);
		return (M)this;
	}

	public java.lang.Integer getTYPE() {
		return getInt("TYPE");
	}

}
