package com.TCA.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseIssueUser<M extends BaseIssueUser<M>> extends Model<M> implements IBean {

	public M setUSERCODE(java.lang.String USERCODE) {
		set("USERCODE", USERCODE);
		return (M)this;
	}

	public java.lang.String getUSERCODE() {
		return getStr("USERCODE");
	}

	public M setNAME(java.lang.String NAME) {
		set("NAME", NAME);
		return (M)this;
	}

	public java.lang.String getNAME() {
		return getStr("NAME");
	}

	public M setDEPT(java.lang.String DEPT) {
		set("DEPT", DEPT);
		return (M)this;
	}

	public java.lang.String getDEPT() {
		return getStr("DEPT");
	}

	public M setSTATE(java.lang.Integer STATE) {
		set("STATE", STATE);
		return (M)this;
	}

	public java.lang.Integer getSTATE() {
		return getInt("STATE");
	}

	public M setNOTE(java.lang.String NOTE) {
		set("NOTE", NOTE);
		return (M)this;
	}

	public java.lang.String getNOTE() {
		return getStr("NOTE");
	}

}
