package com.TCA.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysdiagrams<M extends BaseSysdiagrams<M>> extends Model<M> implements IBean {

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setPrincipalId(java.lang.Integer principalId) {
		set("principal_id", principalId);
		return (M)this;
	}

	public java.lang.Integer getPrincipalId() {
		return getInt("principal_id");
	}

	public M setDiagramId(java.lang.Integer diagramId) {
		set("diagram_id", diagramId);
		return (M)this;
	}

	public java.lang.Integer getDiagramId() {
		return getInt("diagram_id");
	}

	public M setVersion(java.lang.Integer version) {
		set("version", version);
		return (M)this;
	}

	public java.lang.Integer getVersion() {
		return getInt("version");
	}

	public M setDefinition(byte[] definition) {
		set("definition", definition);
		return (M)this;
	}

	public byte[] getDefinition() {
		return get("definition");
	}

}
