package com.TCA.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLimitDeviceTool<M extends BaseLimitDeviceTool<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}

	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setCOSTUNIT(java.lang.String COSTUNIT) {
		set("COSTUNIT", COSTUNIT);
		return (M)this;
	}

	public java.lang.String getCOSTUNIT() {
		return getStr("COSTUNIT");
	}

	public M setWORKPLACE(java.lang.String WORKPLACE) {
		set("WORKPLACE", WORKPLACE);
		return (M)this;
	}

	public java.lang.String getWORKPLACE() {
		return getStr("WORKPLACE");
	}

	public M setTOOLID(java.lang.String TOOLID) {
		set("TOOLID", TOOLID);
		return (M)this;
	}

	public java.lang.String getTOOLID() {
		return getStr("TOOLID");
	}

	public M setCOUNT(java.lang.Integer COUNT) {
		set("COUNT", COUNT);
		return (M)this;
	}

	public java.lang.Integer getCOUNT() {
		return getInt("COUNT");
	}

	public M setTYPE(java.lang.Integer TYPE) {
		set("TYPE", TYPE);
		return (M)this;
	}

	public java.lang.Integer getTYPE() {
		return getInt("TYPE");
	}

	public M setSTATE(java.lang.Integer STATE) {
		set("STATE", STATE);
		return (M)this;
	}

	public java.lang.Integer getSTATE() {
		return getInt("STATE");
	}

	public M setNOTE(java.lang.String NOTE) {
		set("NOTE", NOTE);
		return (M)this;
	}

	public java.lang.String getNOTE() {
		return getStr("NOTE");
	}

}
