package com.TCA.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTcaIssueTerm<M extends BaseTcaIssueTerm<M>> extends Model<M> implements IBean {

	public M setTOOLID(java.lang.String TOOLID) {
		set("TOOLID", TOOLID);
		return (M)this;
	}

	public java.lang.String getTOOLID() {
		return getStr("TOOLID");
	}

	public M setTYPE(java.lang.Short TYPE) {
		set("TYPE", TYPE);
		return (M)this;
	}

	public java.lang.Short getTYPE() {
		return getShort("TYPE");
	}

	public M setSTATE(java.lang.Short STATE) {
		set("STATE", STATE);
		return (M)this;
	}

	public java.lang.Short getSTATE() {
		return getShort("STATE");
	}

	public M setTIMEVAL(java.lang.Integer TIMEVAL) {
		set("TIMEVAL", TIMEVAL);
		return (M)this;
	}

	public java.lang.Integer getTIMEVAL() {
		return getInt("TIMEVAL");
	}

	public M setTIMETYPE(java.lang.Short TIMETYPE) {
		set("TIMETYPE", TIMETYPE);
		return (M)this;
	}

	public java.lang.Short getTIMETYPE() {
		return getShort("TIMETYPE");
	}

	public M setNOTE(java.lang.String NOTE) {
		set("NOTE", NOTE);
		return (M)this;
	}

	public java.lang.String getNOTE() {
		return getStr("NOTE");
	}

}
