package com.TCA.common.model;

import com.TCA.common.model.base.BaseIssueTerm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IssueTerm extends BaseIssueTerm<IssueTerm> {
	public static final IssueTerm dao = new IssueTerm().dao();
}
