package com.TCA.common.model;

import com.TCA.common.model.base.BaseIssueRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IssueRecord extends BaseIssueRecord<IssueRecord> {
	public static final IssueRecord dao = new IssueRecord().dao();
}
