package com.TCA.common.model;

import com.TCA.common.model.base.BaseIssueUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IssueUser extends BaseIssueUser<IssueUser> {
	public static final IssueUser dao = new IssueUser().dao();
}
