package com.TCA.common.model;

import com.TCA.common.model.base.BaseLimitUserTool;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LimitUserTool extends BaseLimitUserTool<LimitUserTool> {
	public static final LimitUserTool dao = new LimitUserTool().dao();
}
