package com.TCA.common.model;

import com.TCA.common.model.base.BaseLimitDeviceTool;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LimitDeviceTool extends BaseLimitDeviceTool<LimitDeviceTool> {
	public static final LimitDeviceTool dao = new LimitDeviceTool().dao();
}
