package com.TCA.common.model;

import com.TCA.common.model.base.BaseLimitTimeTool;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LimitTimeTool extends BaseLimitTimeTool<LimitTimeTool> {
	public static final LimitTimeTool dao = new LimitTimeTool().dao();
}
