package com.TCA.common.model;

import com.TCA.common.model.base.BaseLimitUserTool;
import com.jfinal.kit.StrKit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LimitUserTool extends BaseLimitUserTool<LimitUserTool> {
	public static final LimitUserTool dao = new LimitUserTool().dao();
	
	private String USERNAME = "";
	
	public String getUSERNAME() {
	    if(StrKit.isBlank(USERNAME)){
		USERNAME = IssueUser.dao.findById(this.getUSERCODE()).getNAME();
		this._getAttrs().put("USERNAME", USERNAME);
	    }
	    return USERNAME;
	}
	
	public void setUSERNAME(String USERNAME) {
	    this.USERNAME = USERNAME;
	}
	
}
